FROM node:8

MAINTAINER Antonio "acdc" Jr. <acdcjunior@gmail.com>

# https://github.com/nodejs/node-gyp/issues/454#issuecomment-134140378
RUN npm install --unsafe-perm -g ethereumjs-testrpc
RUN npm install --unsafe-perm -g truffle

EXPOSE 8545
